### PR TITLE
Bump to 4.0.0.3+70+g36ab6660-0debathena1

### PR DESCRIPTION
**Pull request by leee**

### CODE REVIEW

**Comment by quentinmit** [comment]
You probably want to take the latest tarball at http://macathena.mit.edu/dist/

**Comment by leee** [comment]
I am experiencing some discomfort from having to pull from XVM. When you update actual macathena in this organization, maybe you can provide releases there so we can pull from GitHub instead.

**Comment by leee** [comment]
I plan on merging this when it gets a week old with no review, in about 2 days time. We can open up getting a different distribution as an issue.

**Review by tthoma24 — APPROVED** [review]

**Comment by leee** [comment]
Thank you, merging 🙂

**Pull request merged**
